# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - loyalitygo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install, build, and test
        working-directory: ./loyaltygo-admin
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Verify Build
        run: |
          ls -la ./loyaltygo-admin/dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./loyaltygo-admin/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    permissions:
      id-token: write
      contents: read
  
    steps:
  
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact
  
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DC3B3B85FCC4B37B11F86D8DE7FC04E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_272EDF2248B24EC7A8C151691CF316F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A734254FB2B439DA6C44A8F21E0BC53 }}
  
      - name: Verify artifact
        run: |
          ls -la ./artifact
  
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'loyalitygo'
          slot-name: 'Production'
          package: ./artifact
